ui/heirloom/ui/routes/purchase_order.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, jsonify
from flask_login import current_user, login_required

from heirloom.ui import db
from heirloom.ui.models.organization import Organization
from heirloom.ui.models.user import User
from heirloom.ui.models.purchase_order import PurchaseOrder, order_status_codes as ORDER_STATUS
from heirloom.ui.forms.purchase_order import PurchaseOrderForm

# ==============================================================================
# purchase order API
# ==============================================================================
# define namespace
bp = Blueprint('purchase_order', __name__)

# set default route
@bp.route('/', methods=['GET', 'POST'])
@login_required
def purchase_order():
    # validate form
    form = PurchaseOrderForm()
    form.selling_organization.choices = [(0, "Vendor")] + [(o.id, o.name) for o in Organization.query.order_by('name')]
    if form.validate_on_submit():
        # form is valid, create the purchase order
        po = PurchaseOrder(
            title=form.title.data, 
            order_details=form.order_details.data, 
            author=current_user, 
            buying_organization=current_user.organization, 
            selling_organization=Organization.query.get(form.selling_organization.data))
        db.session.add(po)
        db.session.commit()
        flash("Succesfully created Purchase Order", category="success")
        return redirect(url_for('purchase_order.purchase_order'))

    else:
        # handle an invalid form
        return render_template('purchase_order.jinja2', title='Purchase Orders', form=form, POs=PurchaseOrder.query.all())

    return render_template('purchase_order.jinja2', title='Purchase Orders', form=form, POs=PurchaseOrder.query.all())


# endpiont for getting purchase order details
@bp.route('/<po_id>', methods=['GET'])
@login_required
def details(po_id):
    # validate the po_id
    po = PurchaseOrder.query.get(po_id)

    if po is None:
        # handle an invalid purchase order ID
        flash("Purchase Order not found", category="error")
        return redirect(url_for('purchase_order.purchase_order'))

    else:
        # handle a valid purchase order ID
        return render_template('po_details/po_details.jinja2', title='Purchase Orders > Details', po=po)


# endpiont for getting all transactions from a purchase order
@bp.route('/<po_id>/transactions', methods=['GET'])
@login_required
def transactions(po_id):
    # validate the po_id
    po = PurchaseOrder.query.get(po_id)

    if po is None:
        # handle an invalid purchase order ID
        return "Purchase Order not found", 400

    else:
        # handle a valid purchase order ID
        transactions = [t.to_dict() for t in po.transactions] # convert to serializable dict list
        return jsonify(transactions), 200


# endpiont for accepting a purchase order
@bp.route('/<po_id>/accept', methods=['GET'])
@login_required
def accept(po_id):
    # check that the current user has the proper role
    if current_user.get_role_name() is not 'Seller':
        flash("You do not have permission to accept this order.", category="warning")
        return redirect(url_for('purchase_order.details', po_id=po_id))

    # validate the po_id
    po = PurchaseOrder.query.get(po_id)

    if po is None:
        # handle an invalid purchase order ID
        flash("Purchase Order not found", category="error")
        return redirect(url_for('purchase_order.purchase_order'))

    if po.selling_organization.id is not current_user.organization.id:
        flash("You do not have permission to accept this order.", category="warning")
        return redirect(url_for('purchase_order.details', po_id=po_id))

    if po.order_status is not ORDER_STATUS['Submitted']:
        flash("You can only accept purchase orders with a status of Submitted", category="warning")
        return redirect(url_for('purchase_order.details', po_id=po_id))
    
    # handle a valid purchase order ID
    po.order_status = ORDER_STATUS['Accepted']
    db.session.add(po)
    db.session.commit()
    flash("Succesfully accepted " + po.title, category="success")
    return redirect(url_for('purchase_order.details', po_id=po.id))


# endpiont for requesting payment for a purchase order
@bp.route('/<po_id>/request_payment', methods=['GET'])
@login_required
def request_payment(po_id):
    # check that the current user has the proper role
    if current_user.get_role_name() is not 'Seller':
        flash("You do not have permission to request payment for this order.", category="warning")
        return redirect(url_for('purchase_order.details', po_id=po.id))

    # validate the po_id
    po = PurchaseOrder.query.get(po_id)

    if po is None:
        # handle an invalid purchase order ID
        flash("Purchase Order not found", category="error")
        return redirect(url_for('purchase_order.purchase_order'))

    if po.selling_organization.id is not current_user.organization.id:
        flash("You do not have permission to accept this order.", category="warning")
        return redirect(url_for('purchase_order.purchase_order'))

    if po.order_status == ORDER_STATUS["Submitted"] or po.order_status == ORDER_STATUS["Declined"]:
        flash("You cannot request payment for an order with status of 'Submitted' or 'Declined'." +
              ORDER_STATUS['Submitted'], category="warning")
        return redirect(url_for('purchase_order.details', po_id=po.id))

    # handle a valid request
    po.order_status = ORDER_STATUS['Finished']
    db.session.add(po)
    db.session.commit()
    flash("Succesfully requested payment for " + po.title, category="success")
    return redirect(url_for('purchase_order.details', po_id=po.id))
# ==============================================================================

ui/heirloom/ui/templates/po_details/delete_dialog.jinja2
<!-- delete PO dialog --> 
<dialog id="delete_dialog" class="mdl-dialog">
    <h4 class="mdl-dialog__title">Delete Purchase Order</h4>
    <form action="" method="post" novalidate id="requestPaymentForm">
        <div class="mdl-dialog__content">
            <button type="button" id="delete_dialog_close" class="mdl-button mdl-button--raised close wide">Cancel</button>
        </div>
    </form>
</dialog>

<!-- delete PO logic --> 
<script>
(function() {
    var dialog = document.querySelector('#delete_dialog');
    var fab = document.querySelector('#delete-fab');

    if (!dialog.showModal) {
        dialogPolyfill.registerDialog(dialog);
    }

    // wire click listeners to each button if it exists
    fab.addEventListener('click', function () {
        dialog.showModal();
    });

    dialog.querySelector('#delete_dialog_close').addEventListener('click', function () {
        dialog.close();
    });
})();
</script>

ui/heirloom/ui/templates/po_details/edit_dialog.jinja2
<!-- edit PO dialog --> 
<dialog id="edit_dialog" class="mdl-dialog">
    <h4 class="mdl-dialog__title">Edit Purchase Order</h4>
    <form action="" method="post" novalidate id="requestPaymentForm">
        <div class="mdl-dialog__content">
            <button type="button" id="edit_dialog_close" class="mdl-button mdl-button--raised close wide">Cancel</button>
        </div>
    </form>
</dialog>

<!-- edit PO logic --> 
<script>
(function() {
    var dialog = document.querySelector('#edit_dialog');
    var fab = document.querySelector('#edit-fab');

    if (!dialog.showModal) {
        dialogPolyfill.registerDialog(dialog);
    }

    // wire click listeners to each button if it exists
    fab.addEventListener('click', function () {
        dialog.showModal();
    });

    dialog.querySelector('#edit_dialog_close').addEventListener('click', function () {
        dialog.close();
    });
})();
</script>

ui/heirloom/ui/templates/po_details/po_details.jinja2
{% extends "base.jinja2" %} {% block content %}
{% set order_status = po.get_order_status_name() %}
{% set user_organizationId = current_user.organization.id %}
{% set selling_organizationId = po.selling_organization.id %}
{% set buying_organizationId = po.buying_organization.id %}
{% set is_pay_requestable = not (order_status == "Submitted" or order_status == "Declined") %}
{% set is_acceptable = order_status == "Submitted" %}
{% set is_editable = order_status == "Submitted" %}
{% set user_is_buyer = user_organizationId == buying_organizationId %}
{% set user_is_seller = user_organizationId == selling_organizationId %}

<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--12-col center">
        <h3>{{po.title}}</h3>
    </div>
</div>

<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--4-col center">
        <table class="mdl-data-table mdl-js-data-table wide">
            <tbody>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric"><strong>Details</strong></td>
                    <td class="mdl-data-table__cell--non-numeric">{{ po.order_details or '--' }}</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric"><strong>Created</strong></td>
                    <td class="mdl-data-table__cell--non-numeric">{{ po.timestamp }}</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric"><strong>Created by</strong></td>
                    <td class="mdl-data-table__cell--non-numeric">{{ po.author.username }} | {{ po.author.email }}</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric"><strong>Buyer</strong></td>
                    <td class="mdl-data-table__cell--non-numeric">{{ po.buying_organization.name}}</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric"><strong>Seller</strong></td>
                    <td class="mdl-data-table__cell--non-numeric">{{ po.selling_organization.name}}</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric"><strong>Order Status</strong></td>
                    <td class="mdl-data-table__cell--non-numeric">{{ po.get_order_status_name() or '--' }}</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric"><strong>Payment Status</strong></td>
                    <td class="mdl-data-table__cell--non-numeric">{{ po.get_payment_status_name() or '--' }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div id="map-container" class="mdl-cell mdl-cell--8-col center half-view-height"></div>
</div>


<!-- fab container --> 
<div class="bottom-right-fab">
    <!-- accept order button -->
    {% if is_acceptable and user_is_seller  %}
        <a type="button" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" href="{{url_for('purchase_order.accept', po_id=po.id)}}">
        <i class="material-icons">done</i>
        </a>
    {% endif %}

    <!-- edit / delete order buttons --> 
    {% if is_editable and user_is_buyer %}
        <button id="edit-fab" type="button" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
        <i class="material-icons">edit</i>
        </button>

        <button id="delete-fab" type="button" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
        <i class="material-icons">delete</i>
        </button>
    {% endif %}

    <!-- request payment button --> 
    {% if is_pay_requestable and user_is_seller  %}
        <button id="request-payment-fab" type="button" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
        <i class="material-icons">attach_money</i>
        </button>
    {% endif %}
</div>

<!-- import necessary dialogs --> 
{% if is_editable and user_is_buyer %}
    {% include 'po_details/edit_dialog.jinja2' %}
    {% include 'po_details/delete_dialog.jinja2' %}
{% endif %}
{% if is_pay_requestable and user_is_seller %}
    {% include 'po_details/request_payment_dialog.jinja2' %}
{% endif %}


<!-- page logic --> 
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script defer src="{{url_for('static', filename='js/po_details.js')}}"></script>

{% endblock %}

ui/heirloom/ui/templates/po_details/request_payment_dialog.jinja2
<!-- request payment dialog --> 
<dialog id="request_payment_dialog" class="mdl-dialog half-wide">
    <h4 class="mdl-dialog__title">Request Payment</h4>
    <div class="mdl-dialog__content center">
        <h3> Confirm request for payment? </h3>
        <br><br><br>
        <a type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored half-wide" href="{{url_for('purchase_order.request_payment', po_id=po.id)}}">Request Payment</a>
        <br><br>
        <button type="button" id="request_payment_dialog_close" class="mdl-button mdl-button--raised close half-wide">Cancel</button>
    </div>
</dialog>

<!-- request payment logic --> 
<script>
(function() {
    var dialog = document.querySelector('#request_payment_dialog');
    var fab = document.querySelector('#request-payment-fab');

    if (!dialog.showModal) {
        dialogPolyfill.registerDialog(dialog);
    }

    // wire click listeners to each button if it exists
    fab.addEventListener('click', function () {
        dialog.showModal();
    });

    dialog.querySelector('#request_payment_dialog_close').addEventListener('click', function () {
        dialog.close();
    });
})();
</script>