ui/heirloom/ui/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired

# form used for logging in
class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Login')

ui/heirloom/ui/forms/organization.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
import phonenumbers

# form for creating new organizations
class OrganizationForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    address = StringField('Address')
    phone = StringField('Phone')
    submit = SubmitField('Create')

    def validate_phone(self, phone):
        if phone.data:
            if len(phone.data) > 16:
                raise ValidationError('Invalid phone number.')
            try:
                input_number = phonenumbers.parse(phone.data)
                if not (phonenumbers.is_valid_number(input_number)):
                    raise ValidationError('Invalid phone number.')
            except:
                try:
                    input_number = phonenumbers.parse("+1"+phone.data)
                    if not (phonenumbers.is_valid_number(input_number)):
                        raise ValidationError('Invalid phone number.')
                except:
                    raise ValidationError('Invalid phone number.')

ui/heirloom/ui/routes/home.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user, login_required

#==============================================================================
# home API 
#==============================================================================
# define namespace
bp = Blueprint('home', __name__)

#set default route
@bp.route('/')
@login_required
def home():
  return render_template('home.jinja2', title='Home')
#==============================================================================

ui/heirloom/ui/routes/login.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse

from heirloom.ui.forms.login import LoginForm
from heirloom.ui.models.user import User

#==============================================================================
# Login API 
#==============================================================================
# define namespace
bp = Blueprint('login', __name__)

# set default route
@bp.route('/')
@login_required
def index():
  return redirect(url_for('home.home'))

# set login route
@bp.route('/login', methods=['GET', 'POST'])
def login():
  # if the user is logged in, redirect home
  if current_user.is_authenticated:
    return redirect(url_for('home.home'))
  
  # validate login form
  form = LoginForm()
  if form.validate_on_submit():
    # form is valid, get user
    user = User.query.filter_by(username=form.username.data).first()

    # check user exists and password is correct
    if user is None or not user.check_password(form.password.data):
      # user is invalid
      flash('Invalid username or password', category="error")
      return render_template('login.jinja2', title='Login', form=form)
    
    # user is valid. Login and redirect
    login_user(user, remember=form.remember_me.data)
    next_page = request.args.get('next')
    if not next_page or url_parse(next_page).netloc != '':
      # default redirect when next_page isn't valid
      return redirect(url_for('home.home'))
    
    # redirect to next_page
    return redirect(next_page)
  
  else:
    # handle an invalid form
    return render_template('login.jinja2', title='Login', form=form)

# set logout route
@bp.route('/logout')
def logout():
  logout_user()
  return redirect(url_for('login.login'))
#==============================================================================

ui/heirloom/ui/routes/organization.py
from flask import Blueprint, render_template, url_for, flash, redirect
from flask_login import current_user, login_required

from heirloom.ui import db
from heirloom.ui.models.organization import Organization
from heirloom.ui.forms.organization import OrganizationForm

# ==============================================================================
# organization API
# ==============================================================================
# define namespace
bp = Blueprint('organization', __name__)

# set default route
@bp.route('/', methods=['GET', 'POST'])
@login_required
def organization():
    # validate form
    form = OrganizationForm()
    if form.validate_on_submit():
        # form is valid, check that current user is an admin
        if current_user.get_role_name() is not 'Admin':
            return redirect(url_for('organization.organization'))
        
        # user is admin, create the organization
        org = Organization(name=form.name.data, address=form.address.data, phone=form.phone.data)
        db.session.add(org)
        db.session.commit()
        flash("Succesfully created organization", category="success")
        return redirect(url_for('organization.organization'))

    else:
        # handle an invalid form
        return render_template('organization.jinja2', title='Organizations', form=form,
            organizations=Organization.query.all())
    
    return render_template('organization.jinja2', title='Organizations', form=form, 
        organizations=Organization.query.all())
# ==============================================================================

ui/heirloom/ui/routes/purchase_order.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, jsonify
from flask_login import current_user, login_required

from heirloom.ui import db
from heirloom.ui.models.organization import Organization
from heirloom.ui.models.user import User
from heirloom.ui.models.purchase_order import PurchaseOrder, order_status_codes as ORDER_STATUS
from heirloom.ui.forms.purchase_order import PurchaseOrderForm

# ==============================================================================
# purchase order API
# ==============================================================================
# define namespace
bp = Blueprint('purchase_order', __name__)

# set default route
@bp.route('/', methods=['GET', 'POST'])
@login_required
def purchase_order():
    # validate form
    form = PurchaseOrderForm()
    form.selling_organization.choices = [(0, "Vendor")] + [(o.id, o.name) for o in Organization.query.order_by('name')]
    if form.validate_on_submit():
        # form is valid, create the purchase order
        po = PurchaseOrder(
            title=form.title.data, 
            order_details=form.order_details.data, 
            author=current_user, 
            buying_organization=current_user.organization, 
            selling_organization=Organization.query.get(form.selling_organization.data))
        db.session.add(po)
        db.session.commit()
        flash("Succesfully created Purchase Order", category="success")
        return redirect(url_for('purchase_order.purchase_order'))

    else:
        # handle an invalid form
        return render_template('purchase_order.jinja2', title='Purchase Orders', form=form, POs=PurchaseOrder.query.all())

    return render_template('purchase_order.jinja2', title='Purchase Orders', form=form, POs=PurchaseOrder.query.all())


# endpiont for getting purchase order details
@bp.route('/<po_id>', methods=['GET'])
@login_required
def details(po_id):
    # validate the po_id
    po = PurchaseOrder.query.get(po_id)

    if po is None:
        # handle an invalid purchase order ID
        flash("Purchase Order not found", category="error")
        return redirect(url_for('purchase_order.purchase_order'))

    else:
        # handle a valid purchase order ID
        return render_template('po_details/po_details.jinja2', title='Purchase Orders > Details', po=po)


# endpiont for getting all transactions from a purchase order
@bp.route('/<po_id>/transactions', methods=['GET'])
@login_required
def transactions(po_id):
    # validate the po_id
    po = PurchaseOrder.query.get(po_id)

    if po is None:
        # handle an invalid purchase order ID
        return "Purchase Order not found", 400

    else:
        # handle a valid purchase order ID
        transactions = [t.to_dict() for t in po.transactions] # convert to serializable dict list
        return jsonify(transactions), 200


# endpiont for accepting a purchase order
@bp.route('/<po_id>/accept', methods=['GET'])
@login_required
def accept(po_id):
    # check that the current user has the proper role
    if current_user.get_role_name() is not 'Seller':
        flash("You do not have permission to accept this order.", category="warning")
        return redirect(url_for('purchase_order.details', po_id=po_id))

    # validate the po_id
    po = PurchaseOrder.query.get(po_id)

    if po is None:
        # handle an invalid purchase order ID
        flash("Purchase Order not found", category="error")
        return redirect(url_for('purchase_order.purchase_order'))

    if po.selling_organization.id is not current_user.organization.id:
        flash("You do not have permission to accept this order.", category="warning")
        return redirect(url_for('purchase_order.details', po_id=po_id))

    if po.order_status is not ORDER_STATUS['Submitted']:
        flash("You can only accept purchase orders with a status of Submitted", category="warning")
        return redirect(url_for('purchase_order.details', po_id=po_id))
    
    # handle a valid purchase order ID
    po.order_status = ORDER_STATUS['Accepted']
    db.session.add(po)
    db.session.commit()
    flash("Succesfully accepted " + po.title, category="success")
    return redirect(url_for('purchase_order.details', po_id=po.id))


# endpiont for requesting payment for a purchase order
@bp.route('/<po_id>/request_payment', methods=['GET'])
@login_required
def request_payment(po_id):
    # check that the current user has the proper role
    if current_user.get_role_name() is not 'Seller':
        flash("You do not have permission to request payment for this order.", category="warning")
        return redirect(url_for('purchase_order.details', po_id=po.id))

    # validate the po_id
    po = PurchaseOrder.query.get(po_id)

    if po is None:
        # handle an invalid purchase order ID
        flash("Purchase Order not found", category="error")
        return redirect(url_for('purchase_order.purchase_order'))

    if po.selling_organization.id is not current_user.organization.id:
        flash("You do not have permission to accept this order.", category="warning")
        return redirect(url_for('purchase_order.purchase_order'))

    if po.order_status == ORDER_STATUS["Submitted"] or po.order_status == ORDER_STATUS["Declined"]:
        flash("You cannot request payment for an order with status of 'Submitted' or 'Declined'." +
              ORDER_STATUS['Submitted'], category="warning")
        return redirect(url_for('purchase_order.details', po_id=po.id))

    # handle a valid request
    po.order_status = ORDER_STATUS['Finished']
    db.session.add(po)
    db.session.commit()
    flash("Succesfully requested payment for " + po.title, category="success")
    return redirect(url_for('purchase_order.details', po_id=po.id))
# ==============================================================================

ui/heirloom/ui/routes/signup.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user

from heirloom.ui import db
from heirloom.ui.forms.signup import SignupForm
from heirloom.ui.models.user import User

#==============================================================================
# Signup API
#==============================================================================
# define namespace
bp = Blueprint('signup', __name__)

# set default route
@bp.route('/', methods=['GET', 'POST'])
def signup():
  # if the user is logged in, redirect home
  if current_user.is_authenticated:
    return redirect(url_for('home.home'))

  # validate signup form
  form = SignupForm()
  if form.validate_on_submit():
    # form is valid, create the user
    user = User(username=form.username.data, email=form.email.data, role=form.role.data)
    user.set_password(form.password.data)
    db.session.add(user)
    db.session.commit()
    flash('Congratulations, you are now a registered user!', category="success")
    return redirect(url_for('login.login'))

  else:
    # handle an invalid form
    return render_template('signup.jinja2', title='Signup', form=form)
#==============================================================================

ui/heirloom/ui/routes/transaction.py
from flask import Blueprint, render_template, url_for, flash, redirect
from flask_login import current_user, login_required

from heirloom.ui import db
from heirloom.ui.models.user import User
from heirloom.ui.models.transaction import Transaction
from heirloom.ui.models.purchase_order import PurchaseOrder, order_status_codes as ORDER_STATUS
from heirloom.ui.forms.transaction import TransactionForm

# ==============================================================================
# transaction API
# ==============================================================================
# define namespace
bp = Blueprint('transaction', __name__)

# set default route
@bp.route('/', methods=['GET', 'POST'])
@login_required
def transaction():
    # create form
    form = TransactionForm()
    purchase_orders = PurchaseOrder.query.order_by('title')
    form.purchase_order_id.choices = [(0, "Purchase Order")] + [(po.id, po.title) for po in purchase_orders]

    # validate form
    if form.validate_on_submit():
        # form is valid, add transaction
        po = PurchaseOrder.query.get(form.purchase_order_id.data)
        po.order_status = ORDER_STATUS['In Progress']
        transaction = Transaction(
            type=form.type.data, 
            notes=form.notes.data, 
            author=current_user, 
            value=form.value.data,
            purchase_order=po)
        db.session.add(po)
        db.session.add(transaction)
        db.session.commit()
        flash("Succesfully added transaction", category="success")
        return redirect(url_for('transaction.transaction'))

    else:
        # handle an invalid form
        return render_template('transaction.jinja2', title='Transactions', form=form, transactions=Transaction.query.all())

    return render_template('transaction.jinja2', title='Transactions', form=form, transactions=Transaction.query.all())


# endpiont for getting transaction details
@bp.route('/<transaction_id>', methods=['GET'])
@login_required
def details(transaction_id):
    # validate the transaction_id
    txn = Transaction.query.get(transaction_id)

    if txn is None:
        # handle an invalid transaction ID
        flash("Transaction not found", category="error")
        return redirect(url_for('transaction.transaction'))

    else:
        # handle a valid purchase order ID
        return render_template('transaction_details.jinja2', title='Transactions > Details', txn=txn)
# ==============================================================================

ui/heirloom/ui/routes/user.py
from flask import Blueprint, render_template, url_for, flash, redirect
from flask_login import current_user, login_required

from heirloom.ui import db
from heirloom.ui.models.organization import Organization
from heirloom.ui.models.user import User
from heirloom.ui.forms.user import UserForm

# ==============================================================================
# user API
# ==============================================================================
# define namespace
bp = Blueprint('user', __name__)

# set default route
@bp.route('/', methods=['GET', 'POST'])
@login_required
def user():
    # check that the current user is an admin
    if current_user.get_role_name() is not 'Admin':
        return redirect(url_for('home.home'))

    # validate form
    form = UserForm()
    form.organization.choices = [(0, "None")] + [(o.id, o.name) for o in Organization.query.order_by('name')]
    if form.validate_on_submit():
        # form is valid, create the new user
        if form.organization.data:
            org = Organization.query.get(form.organization.data)
            user = User(username=form.username.data, email=form.email.data, 
                role=form.role.data, organization=org)
        else:
            user = User(username=form.username.data, email=form.email.data, role=form.role.data)

        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Succesfully created new user", category="success")
        return redirect(url_for('user.user'))

    else:
        # handle an invalid form
        return render_template('user.jinja2', title='Users', form=form, users=User.query.all())

    return render_template('user.jinja2', title='Users', form=form, users=User.query.all())
# ==============================================================================

ui/heirloom/ui/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Heirloom</title>

    <link rel="shortcut icon" href="{{url_for('static', filename='favicons/favicon-96x96.png')}}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue-red.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/getmdl-select.min.css')}}">
    <style>
      #view-source {
        position: fixed;
        display: block;
        right: 0;
        bottom: 0;
        margin-right: 40px;
        margin-bottom: 40px;
        z-index: 900;
      }
    </style>
  </head>
  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <div class="mdl-layout-spacer"></div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                      mdl-textfield--floating-label mdl-textfield--align-right">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="fixed-header-drawer-exp">
              <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" name="sample" id="fixed-header-drawer-exp">
            </div>
          </div>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">{{title}}</span>
        <nav class="mdl-navigation">
          {% if current_user.is_anonymous %}
            <a class="mdl-navigation__link" href="{{ url_for('login.login') }}">Login</a>
            <a class="mdl-navigation__link" href="{{ url_for('signup.signup') }}">Signup</a>
          {% else %}
            <a class="mdl-navigation__link" href="{{ url_for('home.home') }}">Home</a>
            <a class="mdl-navigation__link" href="{{ url_for('login.logout') }}">Logout</a>
          {% endif %}
        </nav>
      </div>
      <main class="mdl-layout__content">
        <div class="page-content">
           {% block content %}{% endblock %}
        </div>
      </main>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script defer src="{{url_for('static', filename='js/getmdl-select.min.js')}}"></script>
  </body>
</html>

ui/heirloom/ui/templates/base.jinja2
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Heirloom</title>

    <link rel="shortcut icon" href="{{url_for('static', filename='favicons/favicon.ico')}}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue_grey-red.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/getmdl-select.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}">
    
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script defer src="{{url_for('static', filename='js/getmdl-select.min.js')}}"></script>
  </head>
  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">{{title}}</span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title center" style="padding-left: 0px;">
          <a href="{{url_for('home.home')}}">
            <img src="{{url_for('static', filename='img/heirloom-icon.png')}}" style="width:30%; margin: 10px;"></img>
          </a>
        </span>
        <nav class="mdl-navigation">
          {% if current_user.is_anonymous %}
            <!-- default anonymous links -->
            <a class="mdl-navigation__link" href="{{ url_for('login.login') }}">Login</a>
            <a class="mdl-navigation__link" href="{{ url_for('signup.signup') }}">Signup</a>

          {% else %}
            <!-- default links -->
            <a class="mdl-navigation__link" href="{{ url_for('home.home') }}">Home</a>
            <a class="mdl-navigation__link" href="{{ url_for('organization.organization') }}">Organizations</a>

            <!-- admin links -->
            {% if current_user.get_role_name() == "Admin" %}
              <a class="mdl-navigation__link" href="{{ url_for('user.user') }}">Users</a>
              <a class="mdl-navigation__link" href="{{ url_for('purchase_order.purchase_order') }}">Purchase Orders</a>
              <a class="mdl-navigation__link" href="{{ url_for('transaction.transaction') }}">Transactions</a>
            {% endif %}

            <!-- buyer links -->
            {% if current_user.get_role_name() == "Buyer" %}
              <a class="mdl-navigation__link" href="{{ url_for('purchase_order.purchase_order') }}">Purchase Orders</a>
              <a class="mdl-navigation__link" href="{{ url_for('transaction.transaction') }}">Transactions</a>
            {% endif %}

            <!-- seller links -->
            {% if current_user.get_role_name() == "Seller" %}
              <a class="mdl-navigation__link" href="{{ url_for('purchase_order.purchase_order') }}">Purchase Orders</a>
              <a class="mdl-navigation__link" href="{{ url_for('transaction.transaction') }}">Transactions</a>
            {% endif %}

            <!-- default logout link -->
            <a class="mdl-navigation__link" href="{{ url_for('login.logout') }}">Logout</a>
          {% endif %}
        </nav>
      </div>
      <main class="mdl-layout__content">
        <div id="flash_msg_container">
          {% for category, message in get_flashed_messages(with_categories=true) %}
            <button type="button" class="mdl-chip flash-{{category}}">
              <span class="mdl-chip__text">{{message}}</span>
            </button>
            <br>
          {% endfor %}
        </div>

        <div class="page-content tall">
           {% block content %}{% endblock %}
        </div>
      </main>
    </div>
  </body>
</html>

ui/heirloom/ui/templates/home.jinja2
{% extends "base.jinja2" %} {% block content %}
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--12-col center">
        <h2>Welcome to Heirloom, {{ current_user.username }}!</h2>
    </div>
</div>
{% endblock %}

ui/heirloom/ui/templates/login.html
{% extends "base.html" %} {% block content %}
<div class="mdl-grid">
    <div class="mdl-layout-spacer"></div>
    <div class="mdl-cell mdl-cell--4-col">
        <h3>Sign In</h3>
        <form action="" method="post" novalidate id="loginForm">
            {{ form.hidden_tag() }}

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                 {{ form.username(size=32, class_='mdl-textfield__input') }}
                <label class="mdl-textfield__label" for="sample3">{{ form.username.label }}</label>
            </div>
            {% for error in form.username.errors %}
            <br>
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
            
            <br><br>
            
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                {{ form.password(size=32, class_='mdl-textfield__input') }}
                <label class="mdl-textfield__label" for="sample3">{{ form.password.label }}</label>
            </div>
            {% for error in form.password.errors %}
            <br>
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

            <br><br><br>

            <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect align-right">
                {{ form.remember_me(class_='mdl-checkbox__input') }} 
                {{ form.remember_me.label }}
            </label>

            <br><br><br>
            
            {{ form.submit(class_='mdl-button mdl-js-button mdl-button--raised mdl-button--colored') }}
        </form>

        {% with messages = get_flashed_messages() %} 
        {% if messages %}
        <ul>
            {% for message in messages %}
            <span style="color: red;">[{{ message }}]</span>
            <br>
            {% endfor %}
        </ul>
        {% endif %} 
        {% endwith %}   
    </div>
    <div class="mdl-layout-spacer"></div>
</div>
{% endblock %}

ui/heirloom/ui/templates/login.jinja2
<!doctype html>
<html lang="en" class="no-scroll">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Heirloom</title>

    <link rel="shortcut icon" href="{{url_for('static', filename='favicons/favicon.ico')}}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue_grey-red.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/getmdl-select.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}">
    
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script defer src="{{url_for('static', filename='js/getmdl-select.min.js')}}"></script>
  </head>
  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base tall wide">
      <main class="mdl-layout__content tall wide">
          <div class="background-div" id="pts-container"></div>

          <div id="flash_msg_container">
          {% for category, message in get_flashed_messages(with_categories=true) %}
              <button type="button" class="mdl-chip flash-{{category}}">
              <span class="mdl-chip__text">{{message}}</span>
              </button>
              <br>
          {% endfor %}
          </div> 

          <div class="overlay tall wide no-scroll">
            <div class="mdl-grid tall">
              <div class="mdl-layout-spacer"></div>
              <div class="mdl-cell mdl-cell--4-col-desktop mdl-cell--12-col-phone mdl-cell--8-col-tablet mdl-cell--middle" >
                  <span class="mdl-layout-title center" style="margin-bottom: 30px;">
                    <a href="{{url_for('home.home')}}">
                      <img src="{{url_for('static', filename='img/heirloom-icon.png')}}" style="width:100px; margin: 10px;"></img>
                    </a>
                  </span>
                  <form action="" method="post" novalidate id="loginForm" style="background-color: white; padding: 30px;">
                      {{ form.hidden_tag() }}

                      <div class="wide center">
                        <h3>Heirloom</h3>
                      </div>

                      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label wide">
                          {{ form.username(size=32, class_='mdl-textfield__input') }}
                          <label class="mdl-textfield__label" for="sample3">{{ form.username.label }}</label>
                      </div>
                      {% for error in form.username.errors %}
                      <br>
                      <span style="color: red;">[{{ error }}]</span>
                      {% endfor %}
                      
                      <br><br>
                      
                      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label wide">
                          {{ form.password(size=32, class_='mdl-textfield__input') }}
                          <label class="mdl-textfield__label" for="sample3">{{ form.password.label }}</label>
                      </div>
                      {% for error in form.password.errors %}
                      <br>
                      <span style="color: red;">[{{ error }}]</span>
                      {% endfor %}

                      <br><br><br>

                      <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect align-right">
                          {{ form.remember_me(class_='mdl-checkbox__input') }} 
                          {{ form.remember_me.label }}
                      </label>

                      <br><br><br>
                      
                      {{ form.submit(class_='mdl-button mdl-js-button mdl-button--raised mdl-button--colored wide') }}

                      <br><br>

                      <div class="center wide">
                        <a href="{{url_for('signup.signup')}}">Signup here.</a>
                      </div>
                  </form>
              </div>
              <div class="mdl-layout-spacer"></div>
            </div>
          </div>

          <!-- page logic --> 
          <script src="https://unpkg.com/pts@0.5.0/dist/pts.min.js"></script>
          <script defer src="{{url_for('static', filename='js/login.js')}}"></script>
      </main>
  </body>
</html>